name: Test

on:
    push:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    test:
        name: PHP ${{ matrix.php-version }} + Symfony ${{ matrix.symfony-version }}
        runs-on: ubuntu-22.04
        continue-on-error: false
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '8.2'
                    - '8.3'
                symfony-version:
                    - '5.4.*'
                    - '6.4.*'
                    - '7.0.*'
                include:
                    - php-version: '8.1'
                      symfony-version: '5.4.*'
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  ini-values: "memory_limit=-1"
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2, flex

            - name: Validate composer.json
              run: composer validate --no-check-lock

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress
              env:
                  SYMFONY_REQUIRE: "${{ matrix.symfony-version }}"

            - name: Setup problem matchers for PHP
              run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

            - name: Setup problem matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: PHPUnit
              run: vendor/bin/phpunit
